version: '3.8'

networks:
  datalogger_net:
    driver: bridge

services:

  java_app:
    container_name: java_app  # Usa solo si la imagen ya está construida y disponible localmente
    image: chrisliter/apiobesidadspringboot
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://34.66.57.179/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

    depends_on:
      - postgres
    networks:
      - datalogger_net

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dataobesidad:/var/lib/postgresql/data
    networks:
      - datalogger_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - datalogger_net
    depends_on:
      - postgres

volumes:
  postgres_dataobesidad:
    driver: local
